[package]
name = "account_multisig"
edition = "2024.beta"
license = "Apache-2.0"
authors = [ "Thouny (thouny@tuta.io)" ]

[dependencies.account_protocol]
local = "../../../move-framework/packages/protocol"

[dependencies.account_extensions]
local = "../../../move-framework/packages/extensions"

[addresses]
account_multisig = "0x2a2fad949635bf1451654174f0666a2e990f2172857ab70fa13cb5f606ce2088"
account_protocol = "0xcababb3174ca41c616a691024e98e37379e15af969e56b5992fa8139c354c6f5"
account_extensions = "0x162a649c6b0edc3bd1385124afdeffd6f85ab578484dad15c82326438219a347"
