[package]
name = "account_multisig"
edition = "2024.beta"
license = "Apache-2.0"
authors = [ "Thouny (thouny@tuta.io)" ]

[dependencies.AccountProtocol]
local = "../../../move-framework/packages/protocol"

[dependencies.AccountExtensions]
local = "../../../move-framework/packages/extensions"

[addresses]
account_multisig = "0x262efd80b137d0b8da1533819a53781edf21300fe5cb6089183bcab93b887e0f"
account_protocol = "0xdbf6eb7acfe83ce0f26fd884ea77b1358395e85dac4c47effd4c50be4d810afc"
account_extensions = "0x1ac1e0ddfc88c189c78a6001a77c80f36a820335448bc110f2885f809e91cb62"
