[package]
name = "account_dao"
edition = "2024.beta"
license = "Apache-2.0"
authors = [ "Thouny (thouny@tuta.io)" ]

[dependencies.account_protocol]
local = "../../../move-framework/packages/protocol"

[dependencies.account_extensions]
local = "../../../move-framework/packages/extensions"

[addresses]
account_dao = "0xd5b916c4eeb291444233f1fc19c1b7bf779d2fbc9661c550010e0250a9702080"
account_protocol = "0xcababb3174ca41c616a691024e98e37379e15af969e56b5992fa8139c354c6f5"
account_extensions = "0x162a649c6b0edc3bd1385124afdeffd6f85ab578484dad15c82326438219a347"
