[package]
name = "AccountDao"
edition = "2024.beta"
license = "Apache-2.0"
authors = [ "Thouny (thouny@tuta.io)" ]

[dependencies.AccountProtocol]
local = "../../../move-framework/packages/protocol"

[dependencies.AccountExtensions]
local = "../../../move-framework/packages/extensions"

[addresses]
account_dao = "0x7a5e095a37f29c55834bfd56508e570e3199ccf2ec0b760680cdf35f5653f8b7"
account_protocol = "0x10c87c29ea5d5674458652ababa246742a763f9deafed11608b7f0baea296484"
account_extensions = "0x87bee60d3ea6dc5b42e1074134373af27733fb3c5ebc3ac8e013901426d85d53"
