[package]
name = "AccountPayment"
edition = "2024.beta"
license = "Apache-2.0"
authors = [ "Thouny (thouny@tuta.io)" ]

[dependencies.AccountProtocol]
git = "https://github.com/account-tech/move-framework.git"
subdir = "packages/protocol"
rev = "main"

[dependencies.AccountExtensions]
git = "https://github.com/account-tech/move-framework.git"
subdir = "packages/extensions"
rev = "main"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "testnet"

[addresses]
account_payment = "0x441919d12ddcce18f31e0d71ee9eda78ae2b89bfc722b0c9b9cc11fed78b497e"
account_protocol = "0x5f7b38cbec63d97799d5b82f5231e030da5f5f0065282a63ab43cdde448d38a5"
account_extensions = "0x352d1a7f5e8564c8015317691511bc155817c7481deb1c66ee2615cfef41244e"
